### ISSUE TITLE
Can't find the Integration

### ISSUE THREAD

**Issue by depasseg** [danobot/meteorologic_metrics#1]
I installed meteorologic_metrics via HACS.  I then reloaded HA.  Went to Integrations expecting to install the integration, but nothing comes up when searching for "met" (I mean there are items that appear, but not this one).  Am I supposed to do something else first?  I added the following yaml to sensor.yaml and added "sensor: !include sensor.yaml" to configuration.yaml, but when I "Check Configuration", the check fails stating "Configuration invalid - Platform error sensor.meteologic_metrics - Integration 'meteologic_metrics' not found."

- platform: meteologic_metrics
  name: "Meteologic Metrics" # optional, use if you want to use mulitple instances
  temp: sensor.shellyht_outdoor_temperature # celsius
  hum: sensor.shellyht_outdoor_humidity
  dew: sensor.bom_perth_dew_point_c # required if you want WBT estimated with dewpoint depression
  pressure: sensor.bom_perth_pressure_mb # millibar == hectopascal == pascal * 100

I thought I heard that something changed with the way platform integration was being handled.  Is this still working for others?

I'm on HA core-2021.11.5, supervisor-2021.10.8, Home Assistant OS 6.6

**Comment by danobot** [comment]
This is my config:
```
sensor:
  - platform: meteorologic_metrics
    name: "Meteorologic Metrics"
    temp: sensor.outside_temp
    hum: sensor.outside_hum
    pressure: sensor.pixel_2_xl_pressure_sensor
```

Did you restart Home asisstant? it sounds like its a installation issue, not configuration issue.
